contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #aaanf channel"
    url: https://nfcore.slack.com/channels/aaanf
    about: Discussion about the nf-core/aaanf pipeline
